### ISSUE TITLE
Tutorial says failIfDataLoss: true should stop .drop function...

### ISSUE THREAD

**Issue by onordberg** [microsoft/delta-kusto#112]
I noticed when running through your tutorial that in [the section on pushing to prod](https://github.com/microsoft/delta-kusto/blob/main/documentation/tutorials/overview-tutorial/README.md#push-those-modifications-to-prod) you write that the push should fail due to there being a `.drop function` in the delta. I'm running on 0.10.5.112 and it does NOT fail. However, it fails when trying to push a `.drop table`.

To me this actually makes sense, but in that case I think the tutorial is wrong.

**Comment by vplauzon** [comment]
You're right.  The doc is wrong:  it protects only against the .drop that provokes data loss.

I'll fix the doc.  Thank you!

**Comment by vplauzon** [comment]
I altered the tutorial to show a failure on a drop table.
