### ISSUE TITLE
Suggestion to add LastMofiedUser for Kusto objects with delta

### ISSUE THREAD

**Issue by chavi-g** [microsoft/delta-kusto#115]
Would it be possible to add a field for getting the mast modified user of a kusto object when a delta exists. This would help with a similar functionality as a "git blame" to figure out who to assign a delta to. 
The `.show journal` command can be used to get this info.

**Comment by vplauzon** [comment]
.show journal keeps data only for 30 days and isn't %100 reliable within that timeframe (it's a best effort journaling).

Consider also that for multiple entities, it would require scanning the .show journal which would be inefficient in general.
