### ISSUE TITLE
Getting error ".create ingestion mapping have duplicates" now that database schema includes ingestion mappings.

### ISSUE THREAD

**Issue by jeremiah-carlin** [microsoft/delta-kusto#120]
Delta-Kusto version 0.10.5.112
ADX version v273.22373

Running delta-kusto against a database with ingestion mappings is causing an error about duplicates in create ingestion commands.  ADX operation log showed both IngestionMappingsShow and DatabaseSchemaShowAsCslScript whenever I run delta-kusto.

I ran `.show database schema as csl script` manually and could see the ingestion mappings come back in the result set which I'm guessing was not always the case and is the reason I am getting errors about duplicates.

Is it possible to add an option to skip ingestion mappings or to drop duplicate ingestion mappings if they are already defined in the csl script?

As part of debugging I also saw that `.create-or-alter ingestion mapping` is coerced into `create ingestion mapping` but it appears the ADX kusto syntax now supports the `.create-or-alter` syntax.

**Comment by vplauzon** [comment]
I believe it is related to mappings now being provided by default in the .show db script command.

It is being fixed in version 0.11.  It should be available for download in a few hours...

**Comment by vplauzon** [comment]
Fixed in https://github.com/microsoft/delta-kusto/releases/tag/0.11.0.115

**Comment by jeremiah-carlin** [comment]
Awesome!  Thanks for the quick response.

Testing out 0.11.0.115 I'm getting the following error when running any command through delta-kusto 

```
❯ bin/0.11.0.115/delta-kusto

delta-kusto 0.11.0.115
Session:  a067593f-4c4c-4634-b672-867885d79ad6

Exception encountered:  System.InvalidOperationException ; Type delta_kusto.CommandLineOptions appears to be immutable, but no constructor found to accept values.
Stack trace:     at CommandLine.Core.InstanceBuilder.BuildImmutable[T](Type, Maybe`1, IEnumerable`1, IEnumerable`1, List`1)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass1_0`1.<Build>b__5()
   at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1, Func`3, IEnumerable`1, StringComparer, Boolean, CultureInfo, Boolean, Boolean, Boolean, IEnumerable`1)
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1)
   at delta_kusto.Program.Main(String[])

```

Should I create a new issue?

**Comment by vplauzon** [comment]
Oh...  that isn't good!  That's an error we had during integration but was supposed to be gone.

I'm looking at it.

**Comment by jeremiah-carlin** [comment]
Thanks! happy to test or provide debugging information if it helps.

**Comment by vplauzon** [comment]
I think I know what it is...

**Comment by jeremiah-carlin** [comment]
Thanks for the quick fix!  The CLI no longer throws the above error but it appears there are still issues with parsing the create ingestion command.

In my results the json mappings appear to be truncated at the first single quote in the mapping definition.  For example the mapping `[{"column":"EventId","path":"$['EventId']","datatype":"","transform":""}]` is output as `[{"column":"EventId","path":"$[` when running through delta-kusto

As a separate note: In attempting to create a simple reproduction of this issue I realized the ingestion mapping script that comes back from `.show database schema as csl script ` causes a syntax error if you attempt to invoke it directly in the dataexplorer editor (even without using delta-kusto to get the ingestion mapping script).  The editor highlights the `table` in the following command:

```
.create-or-alter table _ingest_test ingestion json mapping _ingest_test_mapping ```
[{"column":"EventId","path":"$['EventId']","datatype":"","transform":""}]
```

**Comment by vplauzon** [comment]
Thank you, I was easily able to repro the issue on my side.  I've sent a bug report to the owner of that command.  Hopefully it should be fixed soon.
