### ISSUE TITLE
Kusto trusted endpoints causing error

### ISSUE THREAD

**Issue by trimbms** [microsoft/delta-kusto#133]
I'm trying to use delta-kusto with a kusto cluster that doesn't end in "kusto.windows.net" but instead with "data.microsoft.com" in an ADO pipeline and I'm experiencing an error that is pretty descriptive "Hostname '<rest_of_url>.data.microsoft.com' is not appearing in the list of the well-known trusted hosts."

Kusto's C# library seems to support not "trusted" endpoints by setting an override to not check if a host is trusted or to add another URL to the trusted host list to allow these other endpoints.
https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto#trusted-endpoints

 Is this functionality able to be turned on for usage with delta-kusto?

**Comment by vplauzon** [comment]
Yes, that shouldn't be too hard to do.

**Comment by vplauzon** [comment]
We could probably issue a fix for that this week.

**Comment by vplauzon** [comment]
It should be fixed in [0.13.1](https://github.com/microsoft/delta-kusto/releases/tag/0.13.1.121).

Please try it and let us know if it did the trick.

**Comment by vplauzon** [comment]
It should be fixed (for real this time) in [0.13.2](https://github.com/microsoft/delta-kusto/releases/tag/0.13.2.122)
