### ISSUE TITLE
CreateFunctionCommand fails on functions with empty lines

### ISSUE THREAD

**Issue by maschAtWork** [microsoft/delta-kusto#142]
Attempting to create a function via `ParseAndCreateCommand` fails when the parsed function has empty lines. I was able to repro the failure, which is thrown from `CreateFunctionCommand::TrimFunctionSchemaBody`, with the below function. 

```
.create-or-alter function aa()
{

// something
range dateHour from 1d to 10d step 1d
}
```

The issue appears to be upstream from `CreateFunctionCommand`, potentially in `KustoCode.Parse`, which only parses `".create-or-alter function with (skipvalidation = \"true\") aa() {"`. Is this empty line behavior expected? If so, should the fix be made in `Kusto.Language` package?

**Comment by vplauzon** [comment]
Delta Kusto assumes each command is separated with one (or many) empty lines.  So it breaks a script into commands by the empty lines.

Having an empty line in a function therefore...  breaks its algorithm (no pun intended).

Workaround would be to remove those empty lines.
