### ISSUE TITLE
Mac OS comptability

### ISSUE THREAD

**Issue by sinaiy** [microsoft/delta-kusto#27]
can you please provide a description how (if) this utility can be used from macos systems

**Comment by vplauzon** [comment]
Hi Sinaiy,


Good catch, I don't think it does at the moment.

Typically the tool is meant to be used in a CI/CD pipeline so on a server.  But for sure you would test your config on a laptop first.

It wouldn't be a huge thing for us to add it to the binaries.  Those are built using [GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on) which offer two different flavours for Mac:

macOS Big Sur 11 | macos-11
macOS Catalina 10.15 | macos-latest&nbsp;or&nbsp;macos-10.15

Which one would make more sense for a Mac Laptop?

**Comment by sinaiy** [comment]
Thank you for the swift reply

macOS Big Sur 11 would be great for my purposes

but even a note on a recommended approach for other operating systems would
be super helpful,
i.e building locally or using a container

Thanks again for the assistance.

sinai

**Comment by vplauzon** [comment]
Have taken a look at the [tutorials section](https://github.com/microsoft/delta-kusto/blob/main/documentation/README.md)?

For instance, the [Azure DevOps tutorial](https://github.com/microsoft/delta-kusto/blob/main/documentation/tutorials/az-dev-ops/README.md) shows a sample of CI / CD pipeline.


Looking further at GitHub action, it seems that *macOS Big Sur 11* is in private preview.  Would something built for *macOS Catalina 10.15* work as well?  It is a CLI so it integrates pretty lightly with the OS...

**Comment by sinaiy** [comment]
it should work,

Thanks again for the effort.

currently, i am running the binaries through a container, which is
perfectly fine for my needs

**Comment by vplauzon** [comment]
Cool.  I'll ping this issue once we get the Mac OS version.

Should be later this week or next week.

**Comment by vplauzon** [comment]
Hi Sinaiy,


Could you take a look at https://github.com/microsoft/delta-kusto/releases/tag/0.3.1.80, download the mac bits and let us know if that works?

**Comment by sinaiy** [comment]
works great!

thanks for the help

**Comment by vplauzon** [comment]
Excellent!

I'll close this issue then.
