### ISSUE TITLE
Support update on 10K databases / 50 objects each

### ISSUE THREAD

**Issue by vplauzon** [microsoft/delta-kusto#56]
First test it to see how it behaves.  Optimize as needed.

**Comment by dmeytin** [comment]
+1.
Thanks a lot for handling this requirement

**Comment by vplauzon** [comment]
Tests done.  1000 dbs took 3 minutes to update 2 tables on.  10 000 dbs should take around 30 minutes.

We've implemented retry and other robustness improvement to insure so a long process would succeed.
