### ISSUE TITLE
Folder name need to be escaped (e.g. ':')

### ISSUE THREAD

**Issue by vplauzon** [microsoft/delta-kusto#61]

**Comment by chavi-g** [comment]
Along with escaping the colon, it would be great if we could escape all the illegal characters, just in case there are some other characters being used in kusto folder names. 
[Illegal characters in windows and liunx](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names)

**Comment by vplauzon** [comment]
Those characters are completely forbidden in paths.  So we can't escape them per se.

I.e. we can replace "a:b" by something like "a::b" or "a\:b".  We could replace them by something legal, e.g. '_', so "a:b" would become "a_b".

Of course the issue with this approach is that "a:b" would then clash with "a?b" since they would both get escaped to "a_b".

Would that be acceptable?

**Comment by chavi-g** [comment]
Yes. For our use we don't need the reverse mapping to get back the original names. It may be an issue for someone if they are looking for that functionality though. But this solution will work for me as I just want to download the functions in folders.

**Comment by vplauzon** [comment]
Fixed in 0.7.2
