### ISSUE TITLE
Delta kusto fails if there is any partitioning policy command identified in the database.

### ISSUE THREAD

**Issue by GowthamDisys** [microsoft/delta-kusto#64]
Hi,

The delta kusto pipeline is failing when there is any partitioning policy in the database. I can see from the documentation that this policy has not been supported yet. But, it should not be making the pipeline fail.

I have added the Azure devops pipeline screenshot for your reference.

![image](https://user-images.githubusercontent.com/62953969/141981603-f64100eb-085c-45b3-b3c0-3f198053e6a7.png)

**Comment by vplauzon** [comment]
Hi Gow,


This is likely related to the fact that Delta Kusto doesn't support partitioning policy yet (cf [Issue 36](https://github.com/microsoft/delta-kusto/issues/36)).

So if you pass that in a script I would expect that error.  If you have that in your database and not in your script, it should do that though.  Can you tell me which one it is?

We can prioritize support for partitioning policy if it is important to you.

**Comment by GowthamDisys** [comment]
Hi Vincent,

I have 2 tasks related to this.

1. To download dev environment scripts, which downloads the kql script(entire schema) of the specified database.(Current-NIL, Target-adx db)

2. To Compare both database and generate delta kql(difference) script.(Current- adx db, Target-adx db)

Both these tasks are failing with the above error.

Thanks,
Gowtham R

**Comment by vplauzon** [comment]
Ok.  We'll investigate.

**Comment by GowthamDisys** [comment]
> Hi Gow,
> 
> This is likely related to the fact that Delta Kusto doesn't support partitioning policy yet (cf [Issue 36](https://github.com/microsoft/delta-kusto/issues/36)).
> 
> So if you pass that in a script I would expect that error. If you have that in your database and not in your script, it should do that though. Can you tell me which one it is?
> 
> We can prioritize support for partitioning policy if it is important to you.

It is a blocker for now and it is stopping us from using the delta kusto on creating the schema in new environment. It would be helpful, if it is sorted out. Thanks!

**Comment by vplauzon** [comment]
We found the source of the issue.

Delta Kusto will ignore the policies it doesn't support in a (real) database.  In a script though, it will block if there is a command it doesn't support.

So if your database contains a partitioning policy, it should ignore it.  If your script contains one, it will block.

So the quick fix would be for you to comment out the partitioning policy in your script.

...  Now there is a second issue.  As your print-screen suggest, your script contains not only the table name but the database it belongs to.  Something like .alter table mydb.mytable policy partitioning...  Although this is legal Kusto, the parser used by Delta Kusto (https://github.com/microsoft/Kusto-Query-Language) is misinterpreting the command as a caching policy.

**Comment by vplauzon** [comment]
So short fix for you would be to comment out the policy in your script.  They won't be delta until that command is supported.

Let me know if that works.

Longer term, we'll submit PR to fix the parser then integrate that in Delta Kusto to fix the db.mytable problem and eventually support the command (https://github.com/microsoft/delta-kusto/issues/36).

**Comment by GowthamDisys** [comment]
In our current devops task, we are using the delta kusto to only find the delta(difference) script between the 2 databases & to store the current database schema as a backup script. When there is a partition policy in the primary database, both the above mentioned tasks are getting failed and we are not able to proceed further. I will attach the parameter files that we used for this operation for your kind reference. 

[download-dev.txt](https://github.com/microsoft/delta-kusto/files/7569557/download-dev.txt)

[compare_db.txt](https://github.com/microsoft/delta-kusto/files/7569554/compare_db.txt)

Thanks!

**Comment by vplauzon** [comment]
Ok, just did a repro.

.show database schema as csl script (which is what Delta Kusto is using to read a db schema) is actually qualifying the table with db name, hence getting seen as caching policy...

We'll check if we can hack that away...

**Comment by vplauzon** [comment]
This should be fixed in version 0.6.2 which has just been released.

Let me know if that fixes your issue so we can close this issue.

As mentioned, that will only ignore the partioning policies.  It won't diff nor apply them.  For that, please follow [issue 36](https://github.com/microsoft/delta-kusto/issues/36) (longer term).

**Comment by vplauzon** [comment]
Oh...  the fix actually introduced another bug.

This should be fixed in 0.6.3.  Would you be so kind to confirm?

**Comment by GowthamDisys** [comment]
Yes Vincent, the fix has introduced another bug. 

We will wait for the next release to fix this issue. Thanks!

**Comment by vplauzon** [comment]
I meant the 0.6.3 is already out.  Did you test it?  It should ignore the partitioning policy.

**Comment by GowthamDisys** [comment]
Oh sorry, I misunderstood! 

Yeah, this version seems to be working fine without any error Vincent. I will let you know if we are facing any issues after further testing. But, we can close this issue now. Thanks for sorting it out!

**Comment by vplauzon** [comment]
Excellent!
