### ISSUE TITLE
Can't Parse Whitespace

### ISSUE THREAD

**Issue by mawarren642** [microsoft/delta-kusto#94]
I am observing an issue with parsing or trimming parts of our schema that seem to be connected to whitespace or empty lines. I am looking at having our team adjust their usage to try and mitigate this issue-- our lead Kusto engineer thinks we should replace occurrences of empty lines with whitespace to `//`, but in the longer term it will be important for us to have this issue mitigated within the application if possible.

Here is a link to the occurrence of the error:
https://msazure.visualstudio.com/One/_releaseProgress?_a=release-environment-logs&releaseId=6305502&environmentId=22941103

Are you able to confirm if there is a better way our team can write their functions that would eliminate this error?

**Comment by vplauzon** [comment]
I don't see how we could handle it on Delta Kusto side.  We need to be able to take a KQL script file, split it in command scripts and then parse it.

The "split it in command scripts" phase is done by looking for empty lines.  That is the same logic than Web UI is doing.

It would be nice to let the parser figure out where commands start and end but unfortunately the parser isn't strong enough for that.

**Comment by mawarren642** [comment]
I've looked into this more with my team and I see what you mean. The functions causing the issue were only able to exist because they were committed to the cluster in a very specific way--highlighting them in Kusto Explorer and using a UI button to submit them. This is certainly an edge case.

I think resolving issues like this is better driven by Kusto documentation in general. I typically use the Microsoft public documentation to investigate these issues but I often find it lacking the level of detail I need in this case. Do you have a recommendation on where else to investigate or how to provide feedback about an issue like this to the kusto developers?

I think you could close this issue, just hoping to see any suggestions you have.

**Comment by vplauzon** [comment]
Yes, by all mean submit feedback on the documentation.  There are links on each documentation page to provide feedback.  This is looked at by the doc-writer thing closely (they have internal dashboards to monitor those, it's not a once-a-year thing).

**Comment by mawarren642** [comment]
Vincent, one of my very smart team members was able to make some changes to your source and mitigate the issue. I have some notes here and will try to re-implement the changes on the newest version of Delta-Kusto as we upgrade. Would you consider also making these changes standard to future version, or explain why if it's a poor idea?

This worked for us for several months without issue using a previous release:

diff --git a/code/DeltaKustoLib/CommandModel/CommandBase.cs b/code/DeltaKustoLib/CommandModel/CommandBase.cs
index 63c7ceb..bc7ddbb 100644
--- a/code/DeltaKustoLib/CommandModel/CommandBase.cs
+++ b/code/DeltaKustoLib/CommandModel/CommandBase.cs
@@ -258,15 +258,13 @@ namespace DeltaKustoLib.CommandModel
         private static IEnumerable<string> SplitCommandScripts(string script)
         {
             var lines = script
-                .Split('\n')
-                .Select(l => l.Trim())
-                //  Remove comment lines
-                .Where(l => !l.StartsWith("//"));
+                .Split('\n');
             var currentCommandLines = new List<string>();
 
             foreach (var line in lines)
             {
-                if (line == string.Empty)
+                string trimmedLine = line.Trim();
+                if (trimmedLine.StartsWith(".alter database") || trimmedLine.StartsWith(".alter table") || trimmedLine.StartsWith(".create-or-alter") || trimmedLine.StartsWith(".create-merge"))
                 {
                     if (currentCommandLines.Any())
                     {
@@ -274,7 +272,8 @@ namespace DeltaKustoLib.CommandModel
                         currentCommandLines.Clear();
                     }
                 }
-                else
+                
+                if (!string.IsNullOrWhiteSpace(trimmedLine))
                 {
                     currentCommandLines.Add(line);
                 }
diff --git a/code/DeltaKustoLib/DeltaKustoLib.csproj b/code/DeltaKustoLib/DeltaKustoLib.csproj
index 7ef30b5..d2efee9 100644
--- a/code/DeltaKustoLib/DeltaKustoLib.csproj
+++ b/code/DeltaKustoLib/DeltaKustoLib.csproj
@@ -14,7 +14,7 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <PackageReference Include="Microsoft.Azure.Kusto.Language" Version="9.3.0-preview" />
+    <PackageReference Include="Microsoft.Azure.Kusto.Language" Version="9.3.1" />
   </ItemGroup>
 
 </Project>
